import React from "react"

export const onRenderBody = ({ setHeadComponents }) => {
  setHeadComponents([
    <link
      key="poppins"
      rel="preload"
      href="/fonts/Poppins/Poppins-Regular.ttf"
      as="font"
      type="font/ttf"
      crossOrigin="anonymous"
    />,
    <link
      key="poppins-medium"
      rel="preload"
      href="/fonts/Poppins/Poppins-Medium.ttf"
      as="font"
      type="font/ttf"
      crossOrigin="anonymous"
    />,
    <link
      key="poppins-bold"
      rel="preload"
      href="/fonts/Poppins/Poppins-Bold.ttf"
      as="font"
      type="font/ttf"
      crossOrigin="anonymous"
    />,
    <link
      key="poppins-extra-bold"
      rel="preload"
      href="/fonts/Poppins/Poppins-ExtraBold.ttf"
      as="font"
      type="font/ttf"
      crossOrigin="anonymous"
    />,
    // Roboto
    <link
      key="roboto-light"
      rel="preload"
      href="/fonts/Roboto/Roboto-Light.ttf"
      as="font"
      type="font/ttf"
      crossOrigin="anonymous"
    />,
    <link
      key="roboto-regular"
      rel="preload"
      href="/fonts/Roboto/Roboto-Regular.ttf"
      as="font"
      type="font/ttf"
      crossOrigin="anonymous"
    />,
    <link
      key="roboto-medium"
      rel="preload"
      href="/fonts/Roboto/Roboto-Medium.ttf"
      as="font"
      type="font/ttf"
      crossOrigin="anonymous"
    />,
    <link
      key="roboto-bold"
      rel="preload"
      href="/fonts/Roboto/Roboto-Bold.ttf"
      as="font"
      type="font/ttf"
      crossOrigin="anonymous"
    />,
  ])
}
